name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        aws-session-token: ${{ secret.AWS_SESSION_TOKEN }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push app image
      run: |
        docker build -t webapp .
        docker tag webapp:latest 420397414401.dkr.ecr.us-east-1.amazonaws.com/app_repo
        docker push 420397414401.dkr.ecr.us-east-1.amazonaws.com/app_repo

    - name: Pull and push MySQL image
      run: |
        docker pull mysql
        docker tag mysql:latest 420397414401.dkr.ecr.us-east-1.amazonaws.com/mysql_repo
        docker push 420397414401.dkr.ecr.us-east-1.amazonaws.com/mysql_repo
